### ISSUE TITLE
Local coverage reporting

### ISSUE THREAD

**Issue by eudoxia0** [fukamachi/cl-coveralls#4]
It would be useful to have a macro we could use to run some code with coverage, but report coverage information to the console, so we don't have to go through the whole commit, push, wait for Travis, wait for Coveralls process to get a basic idea of whether a change increases or decreases coverage.

**Comment by fukamachi** [comment]
Please take a look at #5.

**Comment by fukamachi** [comment]
Closing as #5 has merged.
