### ISSUE TITLE
"output operation on closed SSL stream"

### ISSUE THREAD

**Issue by noctuid** [fukamachi/cl-coveralls#8]
All my tests are passing successfully, and `calc-coverage` works locally. It fails when sending the report to coveralls ([backtrace here](https://travis-ci.org/noctuid/cl-chronicler/jobs/106902875#L515)). I followed all the instructions for creating the [.travis.yml](https://github.com/noctuid/cl-chronicler/blob/master/.travis.yml) with roswell and am using run-prove with COVERALLS=true for sbcl only. I've enable the repo on coveralls. Any ideas as to why this is happening?

I'm not sure if this problems is being caused by misconfiguration on my part and not cl-coveralls. I apologize if I have done something incorrectly.

**Comment by fukamachi** [comment]
I assume it's a fault of Coveralls.io since it's probably already resolved.

**Comment by noctuid** [comment]
Thanks. I retried it quite a few times, but it just wasn't working that day. Now there is no problem.
